apiVersion: v1
kind: Service
metadata:
  name: devops-presentation-service
  namespace: devops-presentation-ns
spec:
  selector:
    app.kubernetes.io/name: devops-presentation
    app.kubernetes.io/instance: devops-presentation-01
    app.kubernetes.io/version: "v1"
    app.kubernetes.io/component: webApp
    app.kubernetes.io/part-of: nothing
    app.kubernetes.io/managed-by: CEDILLE
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
  type: NodePort

